// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxgZjd8usphZj9ytOjOfirnHzj_PYrd9E',
    appId: '1:22592818809:web:0657ebff81c616b442cea8',
    messagingSenderId: '22592818809',
    projectId: 'ecommerceapp-6694d',
    authDomain: 'ecommerceapp-6694d.firebaseapp.com',
    storageBucket: 'ecommerceapp-6694d.appspot.com',
    measurementId: 'G-Q8M6L6Y2PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm6arqgwoKkfdzlT4hoQ-ueFJR_SXwLcw',
    appId: '1:22592818809:android:dc597ee95b0253e642cea8',
    messagingSenderId: '22592818809',
    projectId: 'ecommerceapp-6694d',
    storageBucket: 'ecommerceapp-6694d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxluCElKt6Im6OxM5tbzGEoWQpjH-8PEU',
    appId: '1:22592818809:ios:595ef19f77201b5b42cea8',
    messagingSenderId: '22592818809',
    projectId: 'ecommerceapp-6694d',
    storageBucket: 'ecommerceapp-6694d.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxluCElKt6Im6OxM5tbzGEoWQpjH-8PEU',
    appId: '1:22592818809:ios:595ef19f77201b5b42cea8',
    messagingSenderId: '22592818809',
    projectId: 'ecommerceapp-6694d',
    storageBucket: 'ecommerceapp-6694d.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxgZjd8usphZj9ytOjOfirnHzj_PYrd9E',
    appId: '1:22592818809:web:d9ab3caee5fcb38d42cea8',
    messagingSenderId: '22592818809',
    projectId: 'ecommerceapp-6694d',
    authDomain: 'ecommerceapp-6694d.firebaseapp.com',
    storageBucket: 'ecommerceapp-6694d.appspot.com',
    measurementId: 'G-NXNYV5E637',
  );
}
